### ISSUE TITLE
install.php der 2.8.4er Reihe ist nicht in Ordnung

### ISSUE THREAD

**Issue by MacKP** [contao-community-alliance/contao-core-hotfix#1]
1. wird auf contao weitergeleitet
2. fehlt in der Datei eigentlich alles andere ^^

**Comment by MacKP** [comment]
Ah, anscheinend nur im patchset komplett im Eimer.
Beim komplett-Paket bitte noch mal nachschauen, siehe Kommentar 10 -> http://c-c-a.org/aktuelles/sicherheitshinweise

**Comment by discordier** [comment]
I repacked it, should be working now.
